extends:
  - eslint:recommended
  - airbnb
  - plugin:react/recommended
  - plugin:prettier/recommended

# parser: babel-eslint

parserOptions:
  ecmaVersion: 9
  sourceType: module
  ecmaFeatures:
    jsx: True

env:
  es6: True

plugins:
  - react

