service: num-api # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: python3.6
  stage: dev
  region: us-east-1

functions:
  hello:
    handler: handler.hello

  get_quiz:
    handler: get_quiz.get_quiz
    events:
      - http:
          path: module/{id}
          method: get
          cors: true
