service: num-api # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

package:
  exclude:
    - mocks/**
    - credentials/**
    - layers/**
    - node_modules/**
    - requirements.txt

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1

functions:
  make_quiz:
    handler: make_quiz.make_quiz
    events:
      - http:
          path: module/{id}
          method: get
          cors: true
          # authorizer: aws_iam
    layers:
      - arn:aws:lambda:us-east-1:347179582831:layer:psycopg2:2
      # - {cf:psycopg2-lambda-layer-dev.Psycopg2Layer}

# Create our resources with separate CloudFormation templates
resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}
